import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Elektra from "@/public/images/elektra.jpg"
import { Button } from "@nextui-org/react";
import Chat from "@/components/Chat";
import LogInButton from "@/components/LogInButton";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="min-h-screen">
            <div className="h-[35vh] bg-[#ffff25] flex justify-center items-center w-full">
              <LogInButton />
              <img src={Elektra.src} alt="elektramx" />
            </div>
            {children}
            <Chat />
          </main>
        </Providers>
      </body>
    </html>
  );
}
